{{- if .Values.apiGateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.apiGateway.gatewayName }}
  labels:
    {{- include "private-ai.labels" . | nindent 4 }}
  {{- with .Values.apiGateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.apiGateway.gatewayClassName }}
  listeners:
  {{- if .Values.apiGateway.listeners.http.enabled }}
  - name: http
    protocol: HTTP
    port: {{ .Values.apiGateway.listeners.http.port }}
    {{- if .Values.apiGateway.listeners.http.hostname }}
    hostname: {{ .Values.apiGateway.listeners.http.hostname }}
    {{- end }}
    allowedRoutes:
      namespaces:
        from: Same
  {{- end }}

  {{- if .Values.apiGateway.listeners.https.enabled }}
  - name: https
    protocol: HTTPS
    port: {{ .Values.apiGateway.listeners.https.port }}
    {{- if .Values.apiGateway.listeners.https.hostname }}
    hostname: {{ .Values.apiGateway.listeners.https.hostname }}
    {{- end }}
    tls:
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: {{ .Values.apiGateway.listeners.https.certificateRef }}
    allowedRoutes:
      namespaces:
        from: Same
  {{- end }}
{{- end }}

