{{- if .Values.externalsecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalsecrets.license.name }}
  {{- with .Values.externalsecrets.license.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "private-ai.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalsecrets.secretstorename }}
    kind: SecretStore
  refreshInterval: {{ .Values.externalsecrets.license.refreshInterval }}
  target:
    name: {{ .Values.externalsecrets.license.name }}
  data:
    - secretKey: license.json
      remoteRef:
        key: {{ .Values.externalsecrets.license.remoteRefKey }}
        property: {{ .Values.externalsecrets.license.licenseProperty }}
{{- end }}
